"""BigA 数据访问层 —— 唯一 DB 入口。

🔴 业务代码不许出现裸 `sqlite3.connect`（tests/test_no_raw_sqlite.py 钉死）。
"""

from .db import (
    DEFAULT_DB_PATH,
    AppendOnlyViolation,
    StoreNotInitialised,
    connect,
    db_path,
    init_schema,
    list_agent_runs,
    load_card_by_record_id,
    load_online_card,
    load_raw_snapshot,
    load_verdict,
    load_verdict_meta,
    load_verdicts,
    next_decision_id,
    reserve_decision_id,
    payload_sha256,
    record_agent_run,
    record_verdict_run,
    save_card,
    save_raw_snapshot,
    save_verdict,
    verify_verdict_refs,
)
from .runs import (
    IllegalTransition,
    UnknownRun,
    current_state,
    open_run,
    run_events,
    run_header,
    run_journey,
    transition,
)
from .schema import SCHEMA_VERSION

__all__ = [
    "DEFAULT_DB_PATH",
    "SCHEMA_VERSION",
    "AppendOnlyViolation",
    "StoreNotInitialised",
    "connect",
    "db_path",
    "init_schema",
    "list_agent_runs",
    "load_card_by_record_id",
    "load_online_card",
    "load_raw_snapshot",
    "load_verdict",
    "load_verdict_meta",
    "load_verdicts",
    "next_decision_id",
    "reserve_decision_id",
    "payload_sha256",
    "record_agent_run",
    "record_verdict_run",
    "save_card",
    "save_verdict",
    "save_raw_snapshot",
    "verify_verdict_refs",
    "IllegalTransition",
    "UnknownRun",
    "current_state",
    "open_run",
    "run_events",
    "run_header",
    "run_journey",
    "transition",
]
